### ISSUE TITLE
LCD Going blank after a few hours

### ISSUE THREAD

**Issue by n781td** [craigmw/CellarWarden#10] opened 2017-06-13 16:32 UTC
After connecting a 20x4 LCD and getting it working, I've noticed all the text will disappear (back-light remains on and I can see the contrast is set correctly) after a few hours. If I reboot the RaspberryPi, it starts working again. Is this a known issue?

**Comment by craigmw** [comment] 2017-06-13 16:58
Are you using the I2C or parallel connection to the LCD board? If the former, I have noticed that the LCD does occasionally stop responding, and I'm not certain why this is. It might be due to some errors on the I2C bus. I plan to provide a fix for this in an upcoming update. For now, you can restart the LCD by unchecking the Use LCD Panel in the Configure/Display tab, hitting Apply, checking this box and then hitting Apply again.

**Comment by n781td** [comment] 2017-06-13 16:59
I am using the parallel connection to the LCD board. I will try the fix you mentioned, thanks.


Trevor Conroy

**Comment by craigmw** [comment] 2017-06-13 17:12
Okay, I'll take a look at the logic to see why this might be happening.

**Comment by craigmw** [comment] 2018-09-29 14:39
I have been unable to reproduce this error after several months of testing. In fact, my wine cellar system has been running without fail for over a year and I have not observed this problem. I have noticed an occasional problem with the I2C connected LCD units, but not with units connected directly with an RPi. I wonder if this might be a hardware issue?

**Comment by craigmw** [comment] 2018-09-29 14:39
Unable to reproduce this error so closing the issue.

**Closed as completed by craigmw** 2018-09-29 14:39 UTC
